// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examen_unidad2_backend.Database;

#nullable disable

namespace examen_unidad2_backend.Migrations
{
    [DbContext(typeof(PacientesDbContext))]
    [Migration("20240405034016_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("examen_unidad2_backend.Entities.PacienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("Altura")
                        .HasColumnType("float")
                        .HasColumnName("altura");

                    b.Property<double>("IMC")
                        .HasColumnType("float")
                        .HasColumnName("imc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<double>("Peso")
                        .HasColumnType("float")
                        .HasColumnName("peso");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", "transaccional");
                });
#pragma warning restore 612, 618
        }
    }
}
